'use strict';

const http = require('http');
const https = require('https');
const net = require('net');
const dgram = require('dgram');
const crypto = require('crypto');
const os = require('os');
const { spawn } = require('child_process');
const { URL, URLSearchParams } = require('url');

const VERSION = 'RT7_PHASE10_DVR_SYSTEM_DIAGNOSTIC_SUITE_V4_FINGERPRINT_ENGINE';
const PORT = Number(process.env.PORT || process.env.RT7_SUITE_PORT || 8090);
const HOST = process.env.RT7_SUITE_HOST || '0.0.0.0';
const MAX_BODY = 128 * 1024;
const COMMON_RTSP_PATHS = ['/main_0','/main_1','/main_2','/main_3','/Streaming/Channels/101','/Streaming/Channels/102','/cam/realmonitor?channel=1&subtype=0','/cam/realmonitor?channel=1&subtype=1','/live/ch00_0','/live/ch00_1','/h264Preview_01_main','/h264Preview_01_sub','/ch1/main','/ch1/sub','/live','/stream1'];
const DEFAULT_PORTS = [80,443,554,8000,8554,8899,34567];
let lastReport = null, lastGatewayReport = null, lastDvrReport = null, lastOnvifReport = null, lastFingerprintReport = null;

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function json(res,code,obj){const b=Buffer.from(JSON.stringify(obj,null,2));res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b);}
function html(res,code,body){const b=Buffer.from(body);res.writeHead(code,{'Content-Type':'text/html; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b);}
function clamp(v,min,max,fallback){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):fallback;}
function uniq(xs){return [...new Set(xs.filter(Boolean))];}
function isRailway(){return Boolean(process.env.RAILWAY_ENVIRONMENT||process.env.RAILWAY_PROJECT_ID||process.env.RAILWAY_SERVICE_ID);}
function isPrivateHost(h){return h==='localhost'||h==='127.0.0.1'||h==='::1'||/^10\./.test(h)||/^192\.168\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||/^169\.254\./.test(h);}
function environment(){return {node:process.version,platform:process.platform,hostname:os.hostname(),railway:isRailway(),time:new Date().toISOString()};}
function normalizeBase(raw){let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s='http://'+s;const u=new URL(s);u.pathname=u.pathname.replace(/\/+$/,'');u.search='';u.hash='';return u.toString().replace(/\/$/,'');}
function join(base,p){return new URL(p,base.endsWith('/')?base:base+'/').toString();}
function maskRtsp(url){return String(url).replace(/(rtsp:\/\/[^:@/]+:)([^@/]*)(@)/i,'$1******$3');}
function validHost(raw){const h=String(raw||'').trim();if(!h||h.length>253||/[:/\\?#@\s]/.test(h))throw new Error('DVR Host 只能填 IP 或網域名稱');if(net.isIP(h))return h;if(!/^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$/.test(h))throw new Error('DVR Host 格式不正確');return h;}
function parsePorts(raw){const src=String(raw||'').trim();const vals=src?src.split(','):DEFAULT_PORTS;return uniq(vals.map(x=>Number(String(x).trim())).filter(x=>Number.isInteger(x)&&x>=1&&x<=65535)).slice(0,16);}
function parsePaths(raw){const src=String(raw||'').trim();const vals=src?src.split(/[\r\n,]+/):COMMON_RTSP_PATHS;return uniq(vals.map(x=>{let p=String(x).trim();if(!p)return '';if(!p.startsWith('/'))p='/'+p;return p.slice(0,300);})).slice(0,24);}
function makeRtsp({host,port,user,password,path}){const auth=user?`${encodeURIComponent(user)}:${encodeURIComponent(password||'')}@`:'';return `rtsp://${auth}${host}:${port}${path}`;}

function tcpProbe(host,port,timeoutMs=1800){return new Promise(resolve=>{const t0=Date.now();const s=net.createConnection({host,port});let done=false;const finish=(status,detail)=>{if(done)return;done=true;s.destroy();resolve({port,status,detail,elapsed_ms:Date.now()-t0});};s.setTimeout(timeoutMs);s.once('connect',()=>finish('OPEN','TCP connected'));s.once('timeout',()=>finish('TIMEOUT',`timeout after ${timeoutMs} ms`));s.once('error',e=>finish('CLOSED',e.code||e.message));});}
function requestBuffer(url,timeoutMs=5000,maxBytes=1024*1024,options={}){return new Promise(resolve=>{const t0=Date.now();let settled=false,total=0;const chunks=[];const u=new URL(url);const lib=u.protocol==='https:'?https:http;const headers={'User-Agent':VERSION,'Accept':'*/*',...(options.headers||{})};if(options.user)headers.Authorization='Basic '+Buffer.from(`${options.user}:${options.password||''}`).toString('base64');const req=lib.request(u,{method:options.method||'GET',headers,rejectUnauthorized:false},res=>{res.on('data',c=>{if(total<maxBytes){const x=c.slice(0,maxBytes-total);chunks.push(x);total+=x.length;}if(total>=maxBytes)req.destroy();});res.on('end',()=>finish({status:res.statusCode||0,headers:res.headers,body:Buffer.concat(chunks),ok:(res.statusCode||0)>=200&&(res.statusCode||0)<300,error:null,authenticated:!!options.user}));});const timer=setTimeout(()=>req.destroy(new Error('timeout')),timeoutMs);function finish(x){if(settled)return;settled=true;clearTimeout(timer);resolve({...x,elapsed_ms:Date.now()-t0});}req.once('error',e=>finish({status:0,headers:{},body:Buffer.concat(chunks),ok:false,error:e.message,authenticated:!!options.user}));req.end();});}
async function requestWithBasicRetry(url,timeoutMs,maxBytes,user,password){const anonymous=await requestBuffer(url,timeoutMs,maxBytes);if(anonymous.status===401&&user){const authenticated=await requestBuffer(url,timeoutMs,maxBytes,{user,password});return {selected:authenticated,anonymous,authenticated};}return {selected:anonymous,anonymous,authenticated:null};}
function runProcess(cmd,args,timeoutMs,maxBytes=512*1024){return new Promise(resolve=>{const t0=Date.now();let out=Buffer.alloc(0),err=Buffer.alloc(0),timed=false,spawnErr=null;const child=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});const add=(a,c)=>a.length>=maxBytes?a:Buffer.concat([a,c.slice(0,maxBytes-a.length)]);child.stdout.on('data',c=>out=add(out,c));child.stderr.on('data',c=>err=add(err,c));child.once('error',e=>spawnErr=e);const timer=setTimeout(()=>{timed=true;child.kill('SIGKILL');},timeoutMs);child.once('close',(code,signal)=>{clearTimeout(timer);resolve({code,signal,timed_out:timed,spawn_error:spawnErr?spawnErr.message:null,stdout:out,stderr:err,elapsed_ms:Date.now()-t0});});});}
async function ffmpegInfo(){const [a,b]=await Promise.all([runProcess('ffmpeg',['-hide_banner','-version'],5000,64*1024),runProcess('ffprobe',['-hide_banner','-version'],5000,64*1024)]);const fmt=r=>{const text=Buffer.concat([r.stdout,r.stderr]).toString('utf8');return {ok:!r.spawn_error&&r.code===0,first_line:text.split(/\r?\n/)[0]||'',elapsed_ms:r.elapsed_ms,error:r.spawn_error};};return {ffmpeg:fmt(a),ffprobe:fmt(b)};}
async function ffprobeRtsp(url,transport,timeoutMs){const r=await runProcess('ffprobe',['-v','error','-rtsp_transport',transport,'-rw_timeout',String(timeoutMs*1000),'-show_entries','format=format_name,duration:stream=index,codec_type,codec_name,width,height,r_frame_rate,avg_frame_rate','-of','json',url],timeoutMs+1500,256*1024);let parsed=null;try{parsed=JSON.parse(r.stdout.toString('utf8'));}catch{}const video=parsed?.streams?.find(s=>s.codec_type==='video')||null;return {ok:r.code===0&&!!video,elapsed_ms:r.elapsed_ms,timed_out:r.timed_out,exit_code:r.code,video,log:r.stderr.toString('utf8').slice(0,6000)};}
async function captureFrame(url,transport,timeoutMs){const r=await runProcess('ffmpeg',['-hide_banner','-loglevel','warning','-rtsp_transport',transport,'-rw_timeout',String(timeoutMs*1000),'-i',url,'-an','-frames:v','1','-f','image2pipe','-vcodec','mjpeg','pipe:1'],timeoutMs+2500,4*1024*1024);const b=r.stdout;const ok=r.code===0&&b.length>=4&&b[0]===0xff&&b[1]===0xd8&&b[b.length-2]===0xff&&b[b.length-1]===0xd9;return {ok,elapsed_ms:r.elapsed_ms,timed_out:r.timed_out,exit_code:r.code,jpeg_bytes:b.length,log:r.stderr.toString('utf8').slice(0,6000)};}
function discoverFromHtml(text){
  if(!text)return[];
  const out=[];
  const patterns=[
    /(?:src|href)\s*=\s*["']([^"']+)["']/gi,
    /fetch\s*\(\s*["']([^"']+)["']/gi,
    /new\s+WebSocket\s*\(\s*["']([^"']+)["']/gi
  ];
  for(const re of patterns){
    let m;
    while((m=re.exec(text))){
      try{
        const value=m[1];
        if(value.startsWith('/')){
          const parsed=new URL(value,'http://x');
          out.push(parsed.pathname+parsed.search);
        }
      }catch{}
    }
  }
  return uniq(out);
}

function parseStatus(obj){if(!obj||typeof obj!=='object')return{};return {state:obj.state??obj.status??null,current_channel:obj.current_channel??obj.channel??null,target_channel:obj.target_channel??null,fps:obj.output_fps??obj.fps??null,frame_age_ms:obj.latest_age_ms??obj.frame_age_ms??null,clients:obj.clients??null,source:obj.source??null,ffmpeg_alive:obj.ffmpeg_alive??null,version:obj.version??null};}
function testMjpeg(url,timeoutMs=10000){return new Promise(resolve=>{const t0=Date.now();let settled=false,buf=Buffer.alloc(0),frames=[];const u=new URL(url);const lib=u.protocol==='https:'?https:http;const req=lib.get(u,{headers:{'User-Agent':VERSION,'Accept':'multipart/x-mixed-replace,image/jpeg,*/*'}},res=>{const ct=String(res.headers['content-type']||'');if((res.statusCode||0)<200||(res.statusCode||0)>=300)return finish({ok:false,status:res.statusCode||0,content_type:ct,error:`HTTP ${res.statusCode}`,frames:0,bytes:[]});res.on('data',c=>{buf=Buffer.concat([buf,c]);if(buf.length>8*1024*1024)buf=buf.slice(-4*1024*1024);while(true){const a=buf.indexOf(Buffer.from([0xff,0xd8]));if(a<0)break;const z=buf.indexOf(Buffer.from([0xff,0xd9]),a+2);if(z<0)break;const jpg=buf.slice(a,z+2);frames.push(jpg);buf=buf.slice(z+2);if(frames.length>=2){req.destroy();return finish({ok:true,status:res.statusCode||200,content_type:ct,error:null,frames:2,bytes:frames.map(x=>x.length),distinct:!frames[0].equals(frames[1])});}}});res.once('end',()=>finish({ok:frames.length>0,status:res.statusCode||0,content_type:ct,error:frames.length?'stream ended':'no JPEG',frames:frames.length,bytes:frames.map(x=>x.length),distinct:frames.length>=2?!frames[0].equals(frames[1]):null}));});const timer=setTimeout(()=>{req.destroy();finish({ok:frames.length>0,status:0,content_type:'',error:frames.length?'timeout after JPEG':'frame timeout',frames:frames.length,bytes:frames.map(x=>x.length),distinct:frames.length>=2?!frames[0].equals(frames[1]):null});},timeoutMs);function finish(x){if(settled)return;settled=true;clearTimeout(timer);resolve({...x,url,elapsed_ms:Date.now()-t0});}req.once('error',e=>{if(e.code==='ECONNRESET'&&frames.length>=2)return;finish({ok:false,status:0,content_type:'',error:e.message,frames:frames.length,bytes:frames.map(x=>x.length)});});});}

async function runGatewayScan(input){const started=Date.now();const base=normalizeBase(input.gateway_url||'http://127.0.0.1:8080');const timeout=clamp(input.timeout_ms,500,30000,5000),frameTimeout=clamp(input.frame_timeout_ms,1000,60000,10000);const u=new URL(base);const report={version:VERSION,module:'GATEWAY_DIAGNOSTIC_V2_COMPAT',generated_at:new Date().toISOString(),input:{gateway_url:base,timeout_ms:timeout,frame_timeout_ms:frameTimeout},environment:{...environment(),loopback:['127.0.0.1','localhost','::1'].includes(u.hostname),target_private:isPrivateHost(u.hostname)},gateway:{},pages:[],discovered_paths:[],api_attempts:[],stream_attempts:[]};report.gateway.tcp=await tcpProbe(u.hostname,Number(u.port||(u.protocol==='https:'?443:80)),timeout);if(report.gateway.tcp.status!=='OPEN'){report.conclusion={code:'GATEWAY_TCP_UNREACHABLE',title:'無法連線 Gateway TCP Port',detail:report.gateway.tcp.detail};report.elapsed_ms=Date.now()-started;lastGatewayReport=report;return report;}
let liveHtml='';for(const p of ['/live.html','/']){const r=await requestBuffer(join(base,p),timeout);const text=r.body.toString('utf8');report.pages.push({path:p,status:r.status,ok:r.ok,content_type:r.headers['content-type']||'',elapsed_ms:r.elapsed_ms,bytes:r.body.length,title:(text.match(/<title[^>]*>([^<]+)/i)||[])[1]||null});if(r.ok&&/text\/html/i.test(String(r.headers['content-type']||''))&&!liveHtml)liveHtml=text;}report.discovered_paths=discoverFromHtml(liveHtml);
let best=null;for(const p of uniq(['/status','/health','/api/channel','/api/status','/api/health','/status.json',...report.discovered_paths.filter(x=>/status|health|channel|state/i.test(x))])){const r=await requestBuffer(join(base,p),timeout,512*1024);let obj=null;try{obj=JSON.parse(r.body.toString('utf8'));}catch{}const parsed=parseStatus(obj);report.api_attempts.push({path:p,status:r.status,ok:r.ok,json_ok:!!obj,elapsed_ms:r.elapsed_ms,content_type:r.headers['content-type']||'',parsed,preview:obj?null:r.body.toString('utf8').slice(0,160)});if(obj&&Object.values(parsed).some(v=>v!==null)&&(!best||p==='/status'))best={path:p,obj,parsed};}if(best){report.gateway.status_path=best.path;Object.assign(report.gateway,best.parsed);report.gateway.raw_status=best.obj;}
const self=report.api_attempts.some(x=>x.parsed?.version===VERSION)||report.pages.some(x=>String(x.title||'').includes('SYSTEM_DIAGNOSTIC_SUITE'));report.environment.self_loop_detected=self;if(self){report.conclusion={code:'SCANNER_LOOPBACK_POINTS_TO_ITSELF',title:'Gateway URL 指向診斷工具自己',detail:isRailway()?'Railway 的 127.0.0.1 是 Railway 容器自己，不是 Windows Gateway。':'Suite 預設使用 8090；Gateway 應使用 8080。請確認 Gateway Base URL。'};report.elapsed_ms=Date.now()-started;lastGatewayReport=report;return report;}
let selected=null;for(const p of uniq([...report.discovered_paths.filter(x=>/mjpg|mjpeg|stream|camera/i.test(x)),'/stream.mjpg','/api/camera/stream','/mjpeg','/video.mjpg'])){const a=await testMjpeg(join(base,p),frameTimeout);report.stream_attempts.push({path:p,...a});if(a.ok&&a.frames>=1){selected={path:p,...a};break;}}report.stream=selected?{ok:true,selected_path:selected.path,frames:selected.frames,bytes:selected.bytes,distinct:selected.distinct,elapsed_ms:selected.elapsed_ms}:{ok:false,selected_path:null};if(selected&&selected.frames>=2&&selected.distinct!==false)report.conclusion={code:'GATEWAY_END_TO_END_SUCCESS',title:'Gateway 端到端診斷成功',detail:'Gateway 狀態與連續 MJPEG 影格均正常。'};else if(selected)report.conclusion={code:'GATEWAY_JPEG_SINGLE_FRAME_ONLY',title:'已取得 JPEG，但尚未確認連續更新',detail:'延長影格逾時後再測試。'};else if(!liveHtml)report.conclusion={code:'GATEWAY_LIVE_PAGE_UNAVAILABLE',title:'Gateway TCP 可連，但 live.html 無法讀取',detail:'請確認 Gateway 已啟動且 Base URL/Port 正確。'};else report.conclusion={code:'GATEWAY_STREAM_PATH_NOT_FOUND',title:'找不到可用 MJPEG 路徑',detail:'請查看自動發現與串流探測結果。'};report.elapsed_ms=Date.now()-started;lastGatewayReport=report;return report;}

async function runDvrScan(input){const started=Date.now();const host=validHost(input.dvr_host||'192.168.0.123');const rtspPort=clamp(input.rtsp_port,1,65535,554),tcpTimeout=clamp(input.tcp_timeout_ms,300,15000,1800),probeTimeout=clamp(input.probe_timeout_ms,1500,30000,6000),transport=input.transport==='udp'?'udp':'tcp',ports=parsePorts(input.ports),paths=parsePaths(input.rtsp_paths);const report={version:VERSION,module:'DVR_NETWORK_RTSP_FFMPEG_V1_COMPAT',generated_at:new Date().toISOString(),input:{dvr_host:host,rtsp_port:rtspPort,user:String(input.user||''),password_masked:input.password?'******':'',transport,ports,rtsp_paths:paths,tcp_timeout_ms:tcpTimeout,probe_timeout_ms:probeTimeout},environment:environment(),host_type:isPrivateHost(host)?'PRIVATE_LAN':'PUBLIC_OR_DOMAIN',network:[],ffmpeg:await ffmpegInfo(),rtsp:{attempts:[],success:null}};for(const p of ports)report.network.push(await tcpProbe(host,p,tcpTimeout));if(!report.ffmpeg.ffmpeg.ok||!report.ffmpeg.ffprobe.ok){report.conclusion={code:'FFMPEG_OR_FFPROBE_UNAVAILABLE',title:'FFmpeg／FFprobe 不可用',detail:'請安裝 FFmpeg 並確認 ffmpeg、ffprobe 已加入 PATH。'};report.elapsed_ms=Date.now()-started;lastDvrReport=report;return report;}
for(const path of paths){const url=makeRtsp({host,port:rtspPort,user:String(input.user||''),password:String(input.password||''),path});const probe=await ffprobeRtsp(url,transport,probeTimeout);let frame=null;if(probe.ok)frame=await captureFrame(url,transport,probeTimeout);const item={path,url:maskRtsp(url),probe,frame};report.rtsp.attempts.push(item);if(probe.ok&&frame?.ok){report.rtsp.success=item;break;}}
const rtspTcp=report.network.find(x=>x.port===rtspPort);if(report.rtsp.success)report.conclusion={code:'RTSP_AND_FFMPEG_SUCCESS',title:'DVR RTSP 與 FFmpeg 測試成功',detail:`找到可用路徑 ${report.rtsp.success.path}，並擷取 JPEG。`};else if(report.host_type==='PRIVATE_LAN'&&isRailway())report.conclusion={code:'PRIVATE_LAN_NOT_REACHABLE_FROM_RAILWAY',title:'Railway 無法直接存取 DVR 私有網段',detail:`${host} 為私有 LAN 位址；請使用本機 Gateway、VPN、反向通道或主動 Relay。`};else if(!rtspTcp||rtspTcp.status!=='OPEN')report.conclusion={code:'RTSP_TCP_PORT_UNREACHABLE',title:'RTSP TCP Port 無法連線',detail:`${host}:${rtspPort} 未開啟或無法到達。`};else report.conclusion={code:'RTSP_PATH_OR_AUTH_FAILED',title:'RTSP Port 可達，但路徑或帳密未成功',detail:'請確認帳號、密碼、通道路徑及 RTSP Transport。'};report.elapsed_ms=Date.now()-started;lastDvrReport=report;return report;}

async function runSystem(input){const started=Date.now();const [gateway,dvr]=await Promise.all([runGatewayScan(input),runDvrScan(input)]);const gatewayOk=gateway.conclusion.code==='GATEWAY_END_TO_END_SUCCESS';const dvrOk=dvr.conclusion.code==='RTSP_AND_FFMPEG_SUCCESS';let conclusion;if(gatewayOk&&dvrOk)conclusion={code:'RT7_SYSTEM_ALL_LOCAL_PATHS_SUCCESS',title:'RT7 DVR 本機系統診斷成功',detail:'DVR RTSP、FFmpeg、Native Gateway 與 MJPEG 均正常。'};else if(gatewayOk)conclusion={code:'GATEWAY_SUCCESS_DVR_DIRECT_TEST_INCOMPLETE',title:'Native Gateway 正常；DVR 直接測試未完全成功',detail:'目前可維持 Gateway 架構，並查看 DVR 模組的帳密、路徑或網路結果。'};else if(dvrOk)conclusion={code:'DVR_RTSP_SUCCESS_GATEWAY_FAILED',title:'DVR RTSP 正常，但 Native Gateway 診斷失敗',detail:'請檢查 Gateway 是否啟動、Port 8080 是否正確及 /stream.mjpg 是否存在。'};else conclusion={code:'SYSTEM_DIAGNOSTIC_FAILED',title:'DVR 與 Gateway 尚未通過完整診斷',detail:'請依兩個模組的結論逐項修正。'};const report={version:VERSION,module:'FULL_SYSTEM',generated_at:new Date().toISOString(),environment:environment(),gateway,dvr,summary:{gateway_ok:gatewayOk,dvr_rtsp_ok:dvrOk,ffmpeg_ok:dvr.ffmpeg?.ffmpeg?.ok===true,ffprobe_ok:dvr.ffmpeg?.ffprobe?.ok===true,cloud_direct_ready:dvrOk&&dvr.host_type!=='PRIVATE_LAN',need_gateway:!(dvrOk&&dvr.host_type!=='PRIVATE_LAN')},conclusion,elapsed_ms:Date.now()-started};lastReport=report;return report;}



function xmlEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
function stripXml(v){return String(v||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function xmlFirst(xml,local){const re=new RegExp(`<(?:(?:[A-Za-z_][\\w.-]*):)?${local}\\b[^>]*>([\\s\\S]*?)<\\/(?:(?:[A-Za-z_][\\w.-]*):)?${local}>`,'i');const m=re.exec(String(xml||''));return m?stripXml(m[1]):null;}
function xmlAll(xml,local){const re=new RegExp(`<(?:(?:[A-Za-z_][\\w.-]*):)?${local}\\b[^>]*>([\\s\\S]*?)<\\/(?:(?:[A-Za-z_][\\w.-]*):)?${local}>`,'gi');const out=[];let m;while((m=re.exec(String(xml||''))))out.push(stripXml(m[1]));return out;}
function attrValue(tag,name){const m=new RegExp(`\\b${name}\\s*=\\s*["']([^"']+)["']`,'i').exec(tag||'');return m?m[1]:null;}
function safeUrl(raw){try{return new URL(String(raw).trim()).toString();}catch{return null;}}
function wsseHeader(user,password,createdOverride){if(!user)return'';const nonce=crypto.randomBytes(16);const created=createdOverride||new Date().toISOString();const digest=crypto.createHash('sha1').update(Buffer.concat([nonce,Buffer.from(created),Buffer.from(String(password||''))])).digest('base64');return `<s:Header><wsse:Security s:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:UsernameToken><wsse:Username>${xmlEsc(user)}</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">${digest}</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">${nonce.toString('base64')}</wsse:Nonce><wsu:Created>${created}</wsu:Created></wsse:UsernameToken></wsse:Security></s:Header>`;}
function soapEnvelope(body,user,password,created){return `<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">${wsseHeader(user,password,created)}<s:Body>${body}</s:Body></s:Envelope>`;}
function soapPost(url,body,{user='',password='',timeoutMs=5000,created=null}={}){return new Promise(resolve=>{const t0=Date.now();let settled=false;let u;try{u=new URL(url);}catch(e){return resolve({ok:false,status:0,error:'invalid URL',elapsed_ms:0,body:''});}const payload=Buffer.from(soapEnvelope(body,user,password,created));const lib=u.protocol==='https:'?https:http;const req=lib.request(u,{method:'POST',headers:{'Content-Type':'application/soap+xml; charset=utf-8','Content-Length':payload.length,'User-Agent':VERSION,'Connection':'close'},rejectUnauthorized:false},res=>{const chunks=[];let total=0;res.on('data',c=>{if(total<1024*1024){chunks.push(c.slice(0,1024*1024-total));total+=c.length;}});res.on('end',()=>finish({ok:(res.statusCode||0)>=200&&(res.statusCode||0)<300,status:res.statusCode||0,error:null,headers:res.headers,body:Buffer.concat(chunks).toString('utf8')}));});const timer=setTimeout(()=>req.destroy(new Error('timeout')),timeoutMs);function finish(x){if(settled)return;settled=true;clearTimeout(timer);resolve({...x,elapsed_ms:Date.now()-t0});}req.once('error',e=>finish({ok:false,status:0,error:e.message,headers:{},body:''}));req.end(payload);});}
function wsDiscovery(timeoutMs=3000){return new Promise(resolve=>{const socket=dgram.createSocket({type:'udp4',reuseAddr:true});const id=`urn:uuid:${crypto.randomUUID()}`;const probe=Buffer.from(`<?xml version="1.0" encoding="UTF-8"?><e:Envelope xmlns:e="http://www.w3.org/2003/05/soap-envelope" xmlns:w="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl"><e:Header><w:MessageID>${id}</w:MessageID><w:To e:mustUnderstand="true">urn:schemas-xmlsoap-org:ws:2005:04:discovery</w:To><w:Action e:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</w:Action></e:Header><e:Body><d:Probe><d:Types>dn:NetworkVideoTransmitter</d:Types></d:Probe></e:Body></e:Envelope>`);const found=new Map();let done=false;const finish=()=>{if(done)return;done=true;try{socket.close();}catch{}resolve([...found.values()]);};socket.on('message',(msg,rinfo)=>{const text=msg.toString('utf8');const xaddrs=xmlAll(text,'XAddrs').flatMap(x=>x.split(/\s+/)).map(safeUrl).filter(Boolean);const scopes=xmlAll(text,'Scopes').flatMap(x=>x.split(/\s+/));const endpoint=xmlFirst(text,'Address');const key=endpoint||xaddrs.join('|')||rinfo.address;found.set(key,{from:rinfo.address,endpoint,xaddrs,scopes,bytes:msg.length});});socket.once('error',()=>finish());socket.bind(0,()=>{try{socket.setMulticastTTL(2);socket.send(probe,3702,'239.255.255.250');}catch{finish();}});setTimeout(finish,timeoutMs);});}
function parseOnvifProfiles(xml){const out=[];const re=/<(?:(?:[A-Za-z_][\w.-]*):)?Profiles\b([^>]*)>([\s\S]*?)<\/(?:(?:[A-Za-z_][\w.-]*):)?Profiles>/gi;let m;while((m=re.exec(xml||''))){const token=attrValue(m[1],'token');out.push({token,name:xmlFirst(m[2],'Name'),video_source_token:xmlFirst(m[2],'SourceToken'),encoding:xmlFirst(m[2],'Encoding'),width:Number(xmlFirst(m[2],'Width'))||null,height:Number(xmlFirst(m[2],'Height'))||null,framerate:Number(xmlFirst(m[2],'FrameRateLimit'))||null,bitrate_kbps:Number(xmlFirst(m[2],'BitrateLimit'))||null});}return out;}
async function runOnvifScan(input){const started=Date.now();const host=validHost(input.onvif_host||input.dvr_host||'192.168.0.123');const ports=parsePorts(input.onvif_ports||'80,8000,8080,8899,5000,2020,10080');const user=String(input.user||'admin').trim();const password=String(input.password||'');const discoveryTimeout=clamp(input.discovery_timeout_ms,500,15000,3000);const requestTimeout=clamp(input.onvif_timeout_ms,1000,30000,6000);const discovery=await wsDiscovery(discoveryTimeout);const discoveredX=uniq(discovery.flatMap(x=>x.xaddrs||[]));const direct=ports.map(p=>`http://${host}:${p}/onvif/device_service`);const candidates=uniq([...discoveredX.filter(x=>{try{return new URL(x).hostname===host;}catch{return false;}}),...direct]);const attempts=[];let success=null;
  for(const url of candidates.slice(0,16)){
    const u=new URL(url);const tcp=await tcpProbe(u.hostname,Number(u.port||(u.protocol==='https:'?443:80)),Math.min(requestTimeout,2500));if(tcp.status!=='OPEN'){attempts.push({url,tcp,system_time:null,device_info:null,capabilities:null});continue;}
    const system_time=await soapPost(url,'<tds:GetSystemDateAndTime xmlns:tds="http://www.onvif.org/ver10/device/wsdl"/>',{timeoutMs:requestTimeout});
    const device_info=await soapPost(url,'<tds:GetDeviceInformation xmlns:tds="http://www.onvif.org/ver10/device/wsdl"/>',{user,password,timeoutMs:requestTimeout});
    const capabilities=await soapPost(url,'<tds:GetCapabilities xmlns:tds="http://www.onvif.org/ver10/device/wsdl"><tds:Category>All</tds:Category></tds:GetCapabilities>',{user,password,timeoutMs:requestTimeout});
    const device={manufacturer:xmlFirst(device_info.body,'Manufacturer'),model:xmlFirst(device_info.body,'Model'),firmware:xmlFirst(device_info.body,'FirmwareVersion'),serial:xmlFirst(device_info.body,'SerialNumber'),hardware_id:xmlFirst(device_info.body,'HardwareId')};
    const xaddrs=xmlAll(capabilities.body,'XAddr').map(safeUrl).filter(Boolean);const media_xaddr=xaddrs.find(x=>/media/i.test(x))||xaddrs[0]||null;
    const item={url,tcp,system_time:{ok:system_time.ok,status:system_time.status,error:system_time.error,fault:xmlFirst(system_time.body,'Reason')||xmlFirst(system_time.body,'Text')},device_info:{ok:device_info.ok,status:device_info.status,error:device_info.error,fault:xmlFirst(device_info.body,'Reason')||xmlFirst(device_info.body,'Text'),...device},capabilities:{ok:capabilities.ok,status:capabilities.status,error:capabilities.error,fault:xmlFirst(capabilities.body,'Reason')||xmlFirst(capabilities.body,'Text'),xaddrs,media_xaddr},profiles:[],stream_uris:[]};
    if(media_xaddr){const profilesRes=await soapPost(media_xaddr,'<trt:GetProfiles xmlns:trt="http://www.onvif.org/ver10/media/wsdl"/>',{user,password,timeoutMs:requestTimeout});item.profiles=parseOnvifProfiles(profilesRes.body);item.profiles_status={ok:profilesRes.ok,status:profilesRes.status,error:profilesRes.error,fault:xmlFirst(profilesRes.body,'Reason')||xmlFirst(profilesRes.body,'Text')};for(const p of item.profiles.slice(0,8)){if(!p.token)continue;const body=`<trt:GetStreamUri xmlns:trt="http://www.onvif.org/ver10/media/wsdl"><trt:StreamSetup><tt:Stream xmlns:tt="http://www.onvif.org/ver10/schema">RTP-Unicast</tt:Stream><tt:Transport xmlns:tt="http://www.onvif.org/ver10/schema"><tt:Protocol>RTSP</tt:Protocol></tt:Transport></trt:StreamSetup><trt:ProfileToken>${xmlEsc(p.token)}</trt:ProfileToken></trt:GetStreamUri>`;const sr=await soapPost(media_xaddr,body,{user,password,timeoutMs:requestTimeout});item.stream_uris.push({profile_token:p.token,profile_name:p.name,ok:sr.ok,status:sr.status,uri:xmlFirst(sr.body,'Uri'),fault:xmlFirst(sr.body,'Reason')||xmlFirst(sr.body,'Text'),error:sr.error});}}
    attempts.push(item);if(device_info.ok||item.profiles.length||item.stream_uris.some(x=>x.uri)){success=item;break;}
  }
  let conclusion;if(success){conclusion={code:'ONVIF_DEVICE_AND_MEDIA_SUCCESS',title:'ONVIF 裝置與媒體服務診斷成功',detail:'已取得 ONVIF 裝置資訊、媒體 Profile 或 RTSP Stream URI。'};}else if(discovery.length){conclusion={code:'ONVIF_DISCOVERED_AUTH_OR_SERVICE_FAILED',title:'已由 WS-Discovery 找到設備，但 ONVIF SOAP 未完成',detail:'請確認 ONVIF 已啟用、帳號密碼、設備時間及 Device Service 路徑。'};}else{conclusion={code:'ONVIF_NOT_DISCOVERED_OR_NOT_ENABLED',title:'未發現可用 ONVIF 服務',detail:'設備可能未啟用 ONVIF、不同網段阻擋 UDP 3702，或使用非標準服務埠。'};}
  const report={version:VERSION,module:'ONVIF_SCANNER_V2',generated_at:new Date().toISOString(),input:{onvif_host:host,onvif_ports:ports,user,password_masked:password?'******':'',discovery_timeout_ms:discoveryTimeout,onvif_timeout_ms:requestTimeout},environment:environment(),discovery,attempts,success,conclusion,elapsed_ms:Date.now()-started};lastOnvifReport=report;return report;
}

function layout(content){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${VERSION}</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#071116;color:#eef6fa;font-family:Arial,"Noto Sans TC",sans-serif}.wrap{max-width:1180px;margin:auto;padding:24px 16px 60px}.card{background:#101d23;border:1px solid #31454f;border-radius:14px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.full{grid-column:1/-1}label{display:block;color:#bcd0db;margin:0 0 5px}input,select,textarea,button{width:100%;padding:11px;border-radius:8px;border:1px solid #47606c;background:#071116;color:#fff;font-size:15px}textarea{min-height:105px}button{background:#1977b6;border:0;font-weight:700;cursor:pointer}.secondary{background:#344b58}.ok{color:#35d07f}.bad{color:#ff6565}.warn{color:#ffc84d}.muted{color:#9fb2bc}.result{font-size:22px;font-weight:800}.metric{font-size:22px;font-weight:800}.code{font:13px Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#03090c;padding:12px;border-radius:8px;max-height:420px;overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px 6px;border-bottom:1px solid #2c4049;vertical-align:top}code{color:#b9e4ff}@media(max-width:760px){.grid,.grid3{grid-template-columns:1fr}.full{grid-column:auto}}</style></head><body><main class="wrap">${content}</main></body></html>`;}
function commonForm(action,label){return `<form class="card grid" method="post" action="${action}"><div class="full"><h2>${label}</h2></div><div class="full"><label>Native Gateway Base URL</label><input name="gateway_url" value="${esc(process.env.RT7_GATEWAY_URL||'http://127.0.0.1:8080')}"></div><div><label>DVR Host</label><input name="dvr_host" value="${esc(process.env.RT7_DVR_HOST||'192.168.0.123')}"></div><div><label>RTSP Port</label><input name="rtsp_port" type="number" value="554"></div><div><label>DVR User</label><input name="user" value="admin"></div><div><label>DVR Password</label><input name="password" type="password" value="password"></div><div><label>RTSP Transport</label><select name="transport"><option value="tcp">TCP</option><option value="udp">UDP</option></select></div><div><label>TCP Ports</label><input name="ports" value="80,443,554,8000,8554,8899,34567"></div><div class="full"><label>RTSP Paths（逗號或換行分隔）</label><textarea name="rtsp_paths">/main_0,/main_1,/main_2,/main_3</textarea></div><div><label>TCP timeout ms</label><input name="tcp_timeout_ms" type="number" value="1800"></div><div><label>RTSP probe timeout ms</label><input name="probe_timeout_ms" type="number" value="6000"></div><div><label>Gateway timeout ms</label><input name="timeout_ms" type="number" value="5000"></div><div><label>MJPEG frame timeout ms</label><input name="frame_timeout_ms" type="number" value="10000"></div><div class="full"><button>${label}</button></div></form>`;}
function home(){const env=environment();return layout(`<h1>RT7 DVR System Diagnostic Suite V4</h1><div class="card"><div class="grid3"><div><div class="muted">執行平台</div><div class="metric">${esc(env.platform)}</div></div><div><div class="muted">Railway</div><div class="metric ${env.railway?'warn':'ok'}">${env.railway?'YES':'NO'}</div></div><div><div class="muted">Suite Port</div><div class="metric">${PORT}</div></div></div><p>V4 Fingerprint Engine：採用多來源加權證據、強弱證據分級、誤判抑制與 Basic Auth 重試。</p><p class="warn">完整設備指紋建議在與 DVR 相同區網的 Windows 電腦執行。</p></div><div class="grid"><form class="card" method="get" action="/fingerprint"><h2>V4：Fingerprint Engine</h2><p>HTTP、登入頁、Header、Cookie、favicon、RTSP、ONVIF、Gateway 綜合辨識。</p><button>開啟</button></form><form class="card" method="get" action="/onvif"><h2>V2：ONVIF Scanner</h2><p>UDP 3702、Device Service、Media Profiles、Stream URI。</p><button>開啟</button></form><form class="card" method="get" action="/system"><h2>完整系統診斷</h2><p>DVR、RTSP、FFmpeg、Gateway、MJPEG。</p><button>開啟</button></form><form class="card" method="get" action="/gateway"><h2>Gateway 診斷</h2><p>相容 Gateway Diagnostic Scanner V2。</p><button>開啟</button></form><form class="card" method="get" action="/dvr"><h2>DVR 能力診斷</h2><p>Network + RTSP + FFmpeg Scanner V1。</p><button>開啟</button></form></div>`);}
function parseForm(p){return {gateway_url:p.get('gateway_url'),dvr_host:p.get('dvr_host'),rtsp_port:p.get('rtsp_port'),user:p.get('user'),password:p.get('password'),transport:p.get('transport'),ports:p.get('ports'),rtsp_paths:p.get('rtsp_paths'),tcp_timeout_ms:p.get('tcp_timeout_ms'),probe_timeout_ms:p.get('probe_timeout_ms'),timeout_ms:p.get('timeout_ms'),frame_timeout_ms:p.get('frame_timeout_ms'),onvif_host:p.get('onvif_host'),onvif_ports:p.get('onvif_ports'),discovery_timeout_ms:p.get('discovery_timeout_ms'),onvif_timeout_ms:p.get('onvif_timeout_ms'),http_ports:p.get('http_ports'),http_paths:p.get('http_paths'),fingerprint_timeout_ms:p.get('fingerprint_timeout_ms')};}
function badge(ok){return `<span class="${ok?'ok':'bad'}">${ok?'PASS':'FAIL'}</span>`;}
const FP_HTTP_PATHS=['/','/index.html','/login','/login.html','/default.html','/favicon.ico','/robots.txt','/doc/','/api/','/ISAPI/System/deviceInfo','/cgi-bin/','/RPC2_Login','/axis-cgi/param.cgi?action=list'];
const BRAND_RULES=[
 {brand:'Hikvision',rules:[['hikvision',45,'content'],['webcomponents',35,'content'],['doc/page/login.asp',35,'content'],['isapi/system/deviceinfo',42,'successful_api'],['<devicename>',18,'successful_api']]},
 {brand:'Dahua',rules:[['dahua',45,'content'],['webplugin.exe',32,'content'],['rpc2_login',35,'successful_api'],['global.login',30,'content'],['realm="login to',12,'header']]},
 {brand:'iCatch / SoCatch',rules:[['icatch',48,'content'],['socatch',48,'content'],['iwatchdvr',45,'content'],['net_video',32,'content'],['dvrlink',32,'content'],['main_0',8,'rtsp_success'],['mini_httpd/1.19',4,'header']]},
 {brand:'XM / Xiongmai',rules:[['xiongmai',48,'content'],['xmeye',42,'content'],['netsurveillance',38,'content'],['genee',28,'content']]},
 {brand:'Uniview',rules:[['uniview',48,'content'],['ezstation',35,'content'],['lapi/',36,'successful_api'],['unv',16,'content']]},
 {brand:'TVT',rules:[['tvt',45,'content'],['nvms',35,'content'],['webrec',35,'content']]},
 {brand:'Axis',rules:[['axis communications',55,'content'],['vapix',42,'content'],['axis-cgi',42,'successful_api']]},
 {brand:'Hanwha',rules:[['hanwha',52,'content'],['wisenet',45,'content'],['samsung techwin',45,'content']]},
 {brand:'Milesight',rules:[['milesight',52,'content'],['ms-cgi',38,'successful_api']]}
];
function fingerprintForm(){return `<form class="card grid" method="post" action="/run/fingerprint"><div class="full"><h2>V4：Fingerprint Engine</h2><p class="muted">V4 只採計實際回應內容、Header、成功 API、ONVIF 廠牌與成功 RTSP 路徑；不會因為「曾經掃描某路徑」就判定品牌。遇到 HTTP 401 時會以輸入帳密重試 Basic Auth。</p></div><div><label>DVR Host</label><input name="dvr_host" value="${esc(process.env.RT7_DVR_HOST||'192.168.0.123')}"></div><div><label>HTTP Ports</label><input name="http_ports" value="80,443,8080,8000"></div><div><label>RTSP Port</label><input name="rtsp_port" type="number" value="554"></div><div><label>User</label><input name="user" value="admin"></div><div><label>Password</label><input name="password" type="password" value="password"></div><div><label>Gateway URL</label><input name="gateway_url" value="http://127.0.0.1:8080"></div><div class="full"><label>HTTP Paths</label><textarea name="http_paths">${FP_HTTP_PATHS.join('\n')}</textarea></div><div class="full"><label>RTSP Paths</label><textarea name="rtsp_paths">/main_0\n/main_1\n/main_2\n/main_3\n/Streaming/Channels/101\n/cam/realmonitor?channel=1&subtype=0\n/live/ch00_0</textarea></div><div><label>Timeout ms</label><input name="fingerprint_timeout_ms" type="number" value="4500"></div><div><label>RTSP Transport</label><select name="transport"><option value="tcp">tcp</option><option value="udp">udp</option></select></div><div class="full"><button>開始 V4 指紋診斷</button></div></form>`;}
function headerSubset(h){const keys=['server','www-authenticate','set-cookie','location','content-type','x-powered-by'];const o={};for(const k of keys)if(h&&h[k]!=null)o[k]=h[k];return o;}
function textSignals(buf){const t=buf.toString('utf8').slice(0,300000);const title=(t.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||null;const scripts=[...t.matchAll(/<script[^>]+src=["']([^"']+)/gi)].map(m=>m[1]).slice(0,30);const cookies=[...t.matchAll(/document\.cookie\s*=\s*["']([^"'=;]+)/gi)].map(m=>m[1]);return {title:title&&title.replace(/<[^>]+>/g,'').trim(),scripts,cookies,text_preview:t.replace(/\s+/g,' ').slice(0,1600)};}
function isGenericErrorPage(x){return [401,403,404,500].includes(x.status)&&/^(401 Unauthorized|403 Forbidden|404 Not Found|500 Internal)/i.test(x.title||'');}
function buildEvidence(httpRows,onvif,dvr){const evidence=[];for(const portRow of httpRows){for(const r of portRow.requests){const body=(r.text_preview||'').toLowerCase();const headers=JSON.stringify(r.headers||{}).toLowerCase();const successful=r.status>=200&&r.status<300;const generic=isGenericErrorPage(r);if(!generic&&body)evidence.push({source:'content',value:body,path:r.path,status:r.status});if(headers)evidence.push({source:'header',value:headers,path:r.path,status:r.status});if(successful&&!generic)evidence.push({source:'successful_api',value:(r.path+' '+body+' '+headers).toLowerCase(),path:r.path,status:r.status});}}
 const oi=onvif?.success?.device_info;if(oi?.manufacturer)evidence.push({source:'onvif',value:String(oi.manufacturer).toLowerCase(),weight:100,detail:oi.manufacturer});
 for(const a of dvr?.rtsp?.attempts||[])if(a.probe?.ok)evidence.push({source:'rtsp_success',value:String(a.path).toLowerCase(),path:a.path,status:200});return evidence;}
function scoreBrands(httpRows,onvif,dvr){const evidence=buildEvidence(httpRows,onvif,dvr);const scores=[];for(const brandRule of BRAND_RULES){let score=0,strong=0;const hits=[];for(const [token,weight,source] of brandRule.rules){for(const e of evidence){if(e.source!==source)continue;if(!e.value.includes(token))continue;score+=weight;if(weight>=30)strong++;hits.push({token,weight,source,path:e.path||null,status:e.status||null});break;}}const oi=onvif?.success?.device_info?.manufacturer;if(oi&&String(oi).toLowerCase().includes(brandRule.brand.split(' / ')[0].toLowerCase())){score+=100;strong++;hits.push({token:String(oi),weight:100,source:'onvif',path:null,status:200});}if(score>0)scores.push({brand:brandRule.brand,score,strong_evidence:strong,hits});}scores.sort((a,b)=>b.score-a.score);return {scores,evidence};}
function selectBrand(scored){const top=scored.scores[0]||null,second=scored.scores[1]||null;if(!top)return {manufacturer:'Unknown Vendor',confidence:10,reason:'NO_VENDOR_EVIDENCE',top:null};const margin=top.score-(second?.score||0);const qualifies=top.score>=35&&top.strong_evidence>=1&&margin>=12;if(!qualifies)return {manufacturer:'Unknown Vendor',confidence:Math.min(39,10+Math.floor(top.score/3)),reason:'INSUFFICIENT_OR_AMBIGUOUS_EVIDENCE',top};const confidence=Math.min(99,45+Math.floor(top.score*0.45)+Math.min(15,Math.floor(margin/3)));return {manufacturer:top.brand,confidence,reason:'WEIGHTED_EVIDENCE_MATCH',top};}
async function runFingerprint(input){const started=Date.now();const host=validHost(input.dvr_host||'192.168.0.123');const timeout=clamp(input.fingerprint_timeout_ms,800,15000,4500);const ports=parsePorts(input.http_ports||'80,443,8080,8000');const paths=parsePaths(input.http_paths||FP_HTTP_PATHS.join('\n'));const user=String(input.user||'admin'),password=String(input.password||'');const httpRows=[];
 for(const port of ports){const tcp=await tcpProbe(host,port,Math.min(timeout,2200));if(tcp.status!=='OPEN'){httpRows.push({port,tcp,requests:[]});continue;}const protocol=port===443?'https':'http';const requests=[];for(const path of paths){const url=`${protocol}://${host}:${port}${path}`;const rr=await requestWithBasicRetry(url,timeout,1024*1024,user,password);const r=rr.selected;const sha256=r.body?.length?crypto.createHash('sha256').update(r.body).digest('hex'):null;const md5=r.body?.length?crypto.createHash('md5').update(r.body).digest('hex'):null;const sig=textSignals(r.body||Buffer.alloc(0));requests.push({path,url,status:r.status,ok:r.ok,error:r.error,elapsed_ms:r.elapsed_ms,bytes:r.body?.length||0,headers:headerSubset(r.headers),sha256,md5,authentication:{anonymous_status:rr.anonymous.status,basic_retry:!!rr.authenticated,basic_status:rr.authenticated?.status||null,basic_success:!!rr.authenticated?.ok},...sig});}httpRows.push({port,tcp,requests});}
 const base={...input,dvr_host:host,ports:String(input.ports||'80,443,554,8000,8554,8899,34567'),probe_timeout_ms:String(Math.max(5000,timeout)),tcp_timeout_ms:'1800'};const dvr=await runDvrScan(base);const onvif=await runOnvifScan({...base,onvif_host:host,onvif_ports:String(input.http_ports||'80,443,8080,8000'),discovery_timeout_ms:'2500',onvif_timeout_ms:String(timeout)});let gateway=null;try{gateway=await runGatewayScan({...base,gateway_url:input.gateway_url||'http://127.0.0.1:8080'});}catch(e){gateway={conclusion:{code:'GATEWAY_TEST_ERROR',detail:e.message}};}
 const scored=scoreBrands(httpRows,onvif,dvr),selected=selectBrand(scored);const rtspOk=!!dvr.rtsp?.success,onvifOk=onvif.conclusion?.code==='ONVIF_DEVICE_AND_MEDIA_SUCCESS',gatewayOk=gateway.conclusion?.code==='GATEWAY_END_TO_END_SUCCESS';let compatibility=0;if(rtspOk)compatibility+=45;if(gatewayOk)compatibility+=35;if(onvifOk)compatibility+=10;if(httpRows.some(x=>x.tcp.status==='OPEN'))compatibility+=10;
 const report={version:VERSION,module:'FINGERPRINT_ENGINE_V4',generated_at:new Date().toISOString(),input:{dvr_host:host,http_ports:ports,rtsp_port:Number(input.rtsp_port||554),user,password_masked:'******',gateway_url:input.gateway_url||'http://127.0.0.1:8080'},environment:environment(),http:httpRows,dvr,onvif,gateway,fingerprint:{manufacturer:selected.manufacturer,confidence_percent:selected.confidence,decision_reason:selected.reason,brand_scores:scored.scores,evidence_count:scored.evidence.length,model:onvif.success?.device_info?.model||null,firmware:onvif.success?.device_info?.firmware||null,serial:onvif.success?.device_info?.serial||null,false_positive_controls:['requested path is never evidence','generic 401/403/404 pages excluded from body evidence','brand requires strong evidence and score margin','HTTP Basic Auth retry on 401']},compatibility:{score:compatibility,rtsp:rtspOk,onvif:onvifOk,gateway:gatewayOk,recommended:gatewayOk?'KEEP_NATIVE_RTSP_GATEWAY':rtspOk?'BUILD_OR_REPAIR_GATEWAY':'VERIFY_DVR_CREDENTIALS_AND_RTSP'},conclusion:{code:gatewayOk&&rtspOk?'FINGERPRINT_ENGINE_AND_GATEWAY_SUCCESS':gatewayOk?'GATEWAY_SUCCESS_FINGERPRINT_PARTIAL':rtspOk?'RTSP_SUCCESS_GATEWAY_FAILED':'FINGERPRINT_ENGINE_INCOMPLETE'},elapsed_ms:Date.now()-started};lastFingerprintReport=report;return report;}
function fingerprintResult(r){const httpRows=r.http.flatMap(p=>p.requests.map(x=>`<tr><td>${p.port}</td><td>${esc(x.path)}</td><td>${x.status||'-'}</td><td>${esc(x.headers.server||'-')}</td><td>${esc(x.title||'-')}</td><td>${x.authentication?.basic_retry?`Basic ${x.authentication.basic_status}`:'-'}</td><td><code>${esc((x.sha256||'').slice(0,16))}</code></td></tr>`)).join('');const scores=(r.fingerprint.brand_scores||[]).map(x=>`<tr><td>${esc(x.brand)}</td><td>${x.score}</td><td>${x.strong_evidence}</td><td>${esc(x.hits.map(h=>`${h.source}:${h.token}(+${h.weight})`).join(', '))}</td></tr>`).join('');return layout(`<h1>V4：Fingerprint Engine 結果</h1><div class="card"><div class="result ${r.compatibility.score>=80?'ok':r.compatibility.score>=45?'warn':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.fingerprint.manufacturer)} — 信心度 ${r.fingerprint.confidence_percent}%</h2><p>判斷：${esc(r.fingerprint.decision_reason)}；RT7 Compatibility Score：<b>${r.compatibility.score}/100</b>；建議：${esc(r.compatibility.recommended)}</p></div><div class="grid3"><div class="card"><div class="muted">RTSP</div><div class="metric">${badge(r.compatibility.rtsp)}</div></div><div class="card"><div class="muted">ONVIF</div><div class="metric">${badge(r.compatibility.onvif)}</div></div><div class="card"><div class="muted">Gateway</div><div class="metric">${badge(r.compatibility.gateway)}</div></div></div><div class="card"><h2>設備資訊</h2><table><tr><th>Manufacturer</th><td>${esc(r.fingerprint.manufacturer)}</td></tr><tr><th>Model</th><td>${esc(r.fingerprint.model||'-')}</td></tr><tr><th>Firmware</th><td>${esc(r.fingerprint.firmware||'-')}</td></tr><tr><th>Evidence Count</th><td>${r.fingerprint.evidence_count}</td></tr><tr><th>RTSP Success Path</th><td>${esc(r.dvr.rtsp?.success?.path||'-')}</td></tr><tr><th>Gateway Stream</th><td>${esc(r.gateway.stream?.selected_path||'-')}</td></tr></table></div><div class="card"><h2>Weighted Brand Evidence</h2><table><tr><th>Brand</th><th>Score</th><th>Strong</th><th>命中特徵</th></tr>${scores||'<tr><td colspan="4">沒有足夠的已知品牌證據；正確顯示 Unknown Vendor。</td></tr>'}</table></div><div class="card"><h2>HTTP Fingerprint / Auth Retry</h2><table><tr><th>Port</th><th>Path</th><th>Status</th><th>Server</th><th>Title</th><th>Auth Retry</th><th>SHA-256</th></tr>${httpRows||'<tr><td colspan="7">無 HTTP 回應</td></tr>'}</table></div><div class="grid"><form method="get" action="/fingerprint"><button>重新測試</button></form><form method="get" action="/api/last-fingerprint-report"><button class="secondary">Fingerprint JSON 報告</button></form></div>`);}
function onvifForm(){return `<form class="card grid" method="post" action="/run/onvif"><div class="full"><h2>V2：ONVIF Scanner</h2><p class="muted">先以 WS-Discovery UDP 3702 探索，再測試標準 Device Service 路徑。</p></div><div><label>DVR / NVR Host</label><input name="onvif_host" value="${esc(process.env.RT7_DVR_HOST||'192.168.0.123')}"></div><div><label>ONVIF 常見 Ports</label><input name="onvif_ports" value="80,8000,8080,8899,5000,2020,10080"></div><div><label>ONVIF User</label><input name="user" value="admin"></div><div><label>ONVIF Password</label><input name="password" type="password" value="password"></div><div><label>WS-Discovery timeout ms</label><input name="discovery_timeout_ms" type="number" value="3000"></div><div><label>SOAP timeout ms</label><input name="onvif_timeout_ms" type="number" value="6000"></div><div class="full"><button>開始 ONVIF 診斷</button></div></form>`;}
function onvifResult(r){const drows=(r.discovery||[]).map(x=>`<tr><td>${esc(x.from)}</td><td>${esc(x.endpoint||'-')}</td><td>${esc((x.xaddrs||[]).join('\n')||'-')}</td><td>${esc((x.scopes||[]).slice(0,4).join('\n')||'-')}</td></tr>`).join('');const arows=(r.attempts||[]).map(x=>`<tr><td>${esc(x.url)}</td><td>${badge(x.tcp?.status==='OPEN')}</td><td>${badge(x.system_time?.ok)}</td><td>${badge(x.device_info?.ok)}</td><td>${badge(x.profiles?.length>0)}</td><td>${esc(x.device_info?.manufacturer||'-')} ${esc(x.device_info?.model||'')}</td><td>${esc(x.profiles?.length||0)}</td></tr>`).join('');const streams=(r.success?.stream_uris||[]).map(x=>`<tr><td>${esc(x.profile_name||x.profile_token)}</td><td>${badge(x.ok&&!!x.uri)}</td><td><code>${esc(x.uri||'-')}</code></td><td>${esc(x.fault||x.error||'')}</td></tr>`).join('');return layout(`<h1>V2：ONVIF Scanner 結果</h1><div class="card"><div class="result ${r.conclusion.code==='ONVIF_DEVICE_AND_MEDIA_SUCCESS'?'ok':r.discovery.length?'warn':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="grid3"><div class="card"><div class="muted">WS-Discovery</div><div class="metric">${r.discovery.length}</div></div><div class="card"><div class="muted">Service Attempts</div><div class="metric">${r.attempts.length}</div></div><div class="card"><div class="muted">Profiles</div><div class="metric">${r.success?.profiles?.length||0}</div></div></div><div class="card"><h2>WS-Discovery</h2><table><tr><th>來源 IP</th><th>Endpoint</th><th>XAddr</th><th>Scopes</th></tr>${drows||'<tr><td colspan="4">未收到 UDP 3702 回覆</td></tr>'}</table></div><div class="card"><h2>ONVIF Device Service</h2><table><tr><th>URL</th><th>TCP</th><th>Time</th><th>Device Info</th><th>Profiles</th><th>設備</th><th>數量</th></tr>${arows||'<tr><td colspan="7">未執行</td></tr>'}</table></div><div class="card"><h2>RTSP Stream URI</h2><table><tr><th>Profile</th><th>結果</th><th>URI</th><th>錯誤</th></tr>${streams||'<tr><td colspan="4">尚未取得 Stream URI</td></tr>'}</table></div><div class="grid"><form method="get" action="/onvif"><button>重新測試</button></form><form method="get" action="/api/last-onvif-report"><button class="secondary">ONVIF JSON 報告</button></form></div>`);}

function gatewayResult(r){const rows=(r.stream_attempts||[]).map(x=>`<tr><td>${esc(x.path)}</td><td>${badge(x.ok)}</td><td>${x.frames||0}</td><td>${esc((x.bytes||[]).join(', '))}</td><td>${esc(x.error||'')}</td></tr>`).join('');return layout(`<h1>Gateway 診斷結果</h1><div class="card"><div class="result ${r.conclusion.code==='GATEWAY_END_TO_END_SUCCESS'?'ok':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="card"><table><tr><th>Gateway</th><td>${esc(r.input.gateway_url)}</td></tr><tr><th>TCP</th><td>${esc(r.gateway.tcp?.status)} — ${esc(r.gateway.tcp?.detail)}</td></tr><tr><th>Gateway Version</th><td>${esc(r.gateway.version||'-')}</td></tr><tr><th>State / CH</th><td>${esc(r.gateway.state??'-')} / ${esc(r.gateway.current_channel??'-')} → ${esc(r.gateway.target_channel??'-')}</td></tr><tr><th>FPS / Age / Clients</th><td>${esc(r.gateway.fps??'-')} / ${esc(r.gateway.frame_age_ms??'-')} ms / ${esc(r.gateway.clients??'-')}</td></tr><tr><th>Stream</th><td>${esc(r.stream?.selected_path||'-')}</td></tr></table></div><div class="card"><h2>MJPEG 探測</h2><table><tr><th>Path</th><th>結果</th><th>Frames</th><th>Bytes</th><th>錯誤</th></tr>${rows||'<tr><td colspan="5">未執行</td></tr>'}</table></div><div class="grid"><form method="get" action="/gateway"><button>重新測試</button></form><form method="get" action="/api/last-gateway-report"><button class="secondary">JSON 報告</button></form></div>`);}
function dvrResult(r){const netRows=r.network.map(x=>`<tr><td>${x.port}</td><td>${badge(x.status==='OPEN')}</td><td>${esc(x.status)}</td><td>${esc(x.detail)}</td><td>${x.elapsed_ms} ms</td></tr>`).join('');const rtspRows=r.rtsp.attempts.map(x=>`<tr><td>${esc(x.path)}</td><td>${badge(x.probe.ok)}</td><td>${badge(x.frame?.ok===true)}</td><td>${esc(x.probe.video?.codec_name||'-')}</td><td>${esc(x.probe.video?`${x.probe.video.width||'-'}x${x.probe.video.height||'-'}`:'-')}</td><td>${x.frame?.jpeg_bytes||0}</td></tr>`).join('');return layout(`<h1>DVR Network + RTSP + FFmpeg 結果</h1><div class="card"><div class="result ${r.conclusion.code==='RTSP_AND_FFMPEG_SUCCESS'?'ok':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="grid3"><div class="card"><div class="muted">FFmpeg</div><div class="metric">${badge(r.ffmpeg.ffmpeg.ok)}</div><small>${esc(r.ffmpeg.ffmpeg.first_line||r.ffmpeg.ffmpeg.error||'')}</small></div><div class="card"><div class="muted">FFprobe</div><div class="metric">${badge(r.ffmpeg.ffprobe.ok)}</div><small>${esc(r.ffmpeg.ffprobe.first_line||r.ffmpeg.ffprobe.error||'')}</small></div><div class="card"><div class="muted">Host Type</div><div class="metric">${esc(r.host_type)}</div></div></div><div class="card"><h2>TCP Port</h2><table><tr><th>Port</th><th>結果</th><th>狀態</th><th>資訊</th><th>耗時</th></tr>${netRows}</table></div><div class="card"><h2>RTSP 路徑</h2><table><tr><th>Path</th><th>Probe</th><th>JPEG</th><th>Codec</th><th>Size</th><th>JPEG Bytes</th></tr>${rtspRows||'<tr><td colspan="6">未執行</td></tr>'}</table></div><div class="grid"><form method="get" action="/dvr"><button>重新測試</button></form><form method="get" action="/api/last-dvr-report"><button class="secondary">JSON 報告</button></form></div>`);}
function systemResult(r){return layout(`<h1>RT7 完整系統診斷結果</h1><div class="card"><div class="result ${r.conclusion.code==='RT7_SYSTEM_ALL_LOCAL_PATHS_SUCCESS'?'ok':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="grid3"><div class="card"><div class="muted">DVR RTSP</div><div class="metric">${badge(r.summary.dvr_rtsp_ok)}</div><p>${esc(r.dvr.conclusion.code)}</p></div><div class="card"><div class="muted">Native Gateway</div><div class="metric">${badge(r.summary.gateway_ok)}</div><p>${esc(r.gateway.conclusion.code)}</p></div><div class="card"><div class="muted">FFmpeg / FFprobe</div><div class="metric">${badge(r.summary.ffmpeg_ok&&r.summary.ffprobe_ok)}</div></div></div><div class="card"><table><tr><th>Cloud Direct Ready</th><td>${r.summary.cloud_direct_ready?'YES':'NO'}</td></tr><tr><th>Need Gateway</th><td>${r.summary.need_gateway?'YES':'NO'}</td></tr><tr><th>Gateway Stream</th><td>${esc(r.gateway.stream?.selected_path||'-')}</td></tr><tr><th>RTSP Success Path</th><td>${esc(r.dvr.rtsp?.success?.path||'-')}</td></tr><tr><th>總耗時</th><td>${r.elapsed_ms} ms</td></tr></table></div><div class="grid"><form method="get" action="/system"><button>重新測試</button></form><form method="get" action="/api/last-report"><button class="secondary">完整 JSON 報告</button></form></div>`);}
async function readBody(req){let body='';req.setEncoding('utf8');for await(const c of req){body+=c;if(body.length>MAX_BODY)throw new Error('request too large');}return new URLSearchParams(body);}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/')return html(res,200,home());if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,version:VERSION,environment:environment(),port:PORT});if(req.method==='GET'&&u.pathname==='/fingerprint')return html(res,200,layout(`<h1>V4：Fingerprint Engine</h1>${fingerprintForm()}`));if(req.method==='GET'&&u.pathname==='/onvif')return html(res,200,layout(`<h1>V2：ONVIF Scanner</h1>${onvifForm()}`));if(req.method==='GET'&&u.pathname==='/system')return html(res,200,layout(`<h1>完整系統診斷</h1>${commonForm('/run/system','開始完整系統診斷')}`));if(req.method==='GET'&&u.pathname==='/gateway')return html(res,200,layout(`<h1>Native Gateway 診斷</h1>${commonForm('/run/gateway','開始 Gateway 診斷')}`));if(req.method==='GET'&&u.pathname==='/dvr')return html(res,200,layout(`<h1>DVR Network + RTSP + FFmpeg</h1>${commonForm('/run/dvr','開始 DVR 能力診斷')}`));if(req.method==='GET'&&u.pathname==='/api/last-fingerprint-report')return json(res,lastFingerprintReport?200:404,lastFingerprintReport||{ok:false,error:'no_fingerprint_report'});if(req.method==='GET'&&u.pathname==='/api/last-onvif-report')return json(res,lastOnvifReport?200:404,lastOnvifReport||{ok:false,error:'no_onvif_report'});if(req.method==='GET'&&u.pathname==='/api/last-report')return json(res,lastReport?200:404,lastReport||{ok:false,error:'no_report'});if(req.method==='GET'&&u.pathname==='/api/last-gateway-report')return json(res,lastGatewayReport?200:404,lastGatewayReport||{ok:false,error:'no_gateway_report'});if(req.method==='GET'&&u.pathname==='/api/last-dvr-report')return json(res,lastDvrReport?200:404,lastDvrReport||{ok:false,error:'no_dvr_report'});if(req.method==='POST'&&u.pathname.startsWith('/run/')){const input=parseForm(await readBody(req));if(u.pathname==='/run/fingerprint')return html(res,200,fingerprintResult(await runFingerprint(input)));if(u.pathname==='/run/onvif')return html(res,200,onvifResult(await runOnvifScan(input)));if(u.pathname==='/run/gateway')return html(res,200,gatewayResult(await runGatewayScan(input)));if(u.pathname==='/run/dvr')return html(res,200,dvrResult(await runDvrScan(input)));if(u.pathname==='/run/system')return html(res,200,systemResult(await runSystem(input)));}return json(res,404,{ok:false,error:'not_found'});}catch(e){return html(res,500,layout(`<h1 class="bad">Diagnostic Error</h1><div class="card code">${esc(e.stack||e)}</div><form method="get" action="/"><button>返回首頁</button></form>`));}});
server.listen(PORT,HOST,()=>{console.log('='.repeat(76));console.log(VERSION);
console.log('V4:     Weighted Fingerprint Engine + false-positive suppression');console.log(`Suite:   http://127.0.0.1:${PORT}`);console.log('Gateway: http://127.0.0.1:8080/live.html');console.log('='.repeat(76));});
