'use strict';

const http = require('http');
const https = require('https');
const net = require('net');
const os = require('os');
const { spawn } = require('child_process');
const { URL, URLSearchParams } = require('url');

const VERSION = 'RT7_PHASE10_DVR_SYSTEM_DIAGNOSTIC_SUITE_V1';
const PORT = Number(process.env.PORT || process.env.RT7_SUITE_PORT || 8090);
const HOST = process.env.RT7_SUITE_HOST || '0.0.0.0';
const MAX_BODY = 128 * 1024;
const COMMON_RTSP_PATHS = ['/main_0','/main_1','/main_2','/main_3','/Streaming/Channels/101','/Streaming/Channels/102','/cam/realmonitor?channel=1&subtype=0','/cam/realmonitor?channel=1&subtype=1','/live/ch00_0','/live/ch00_1','/h264Preview_01_main','/h264Preview_01_sub','/ch1/main','/ch1/sub','/live','/stream1'];
const DEFAULT_PORTS = [80,443,554,8000,8554,8899,34567];
let lastReport = null, lastGatewayReport = null, lastDvrReport = null;

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function json(res,code,obj){const b=Buffer.from(JSON.stringify(obj,null,2));res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b);}
function html(res,code,body){const b=Buffer.from(body);res.writeHead(code,{'Content-Type':'text/html; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b);}
function clamp(v,min,max,fallback){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):fallback;}
function uniq(xs){return [...new Set(xs.filter(Boolean))];}
function isRailway(){return Boolean(process.env.RAILWAY_ENVIRONMENT||process.env.RAILWAY_PROJECT_ID||process.env.RAILWAY_SERVICE_ID);}
function isPrivateHost(h){return h==='localhost'||h==='127.0.0.1'||h==='::1'||/^10\./.test(h)||/^192\.168\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||/^169\.254\./.test(h);}
function environment(){return {node:process.version,platform:process.platform,hostname:os.hostname(),railway:isRailway(),time:new Date().toISOString()};}
function normalizeBase(raw){let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s='http://'+s;const u=new URL(s);u.pathname=u.pathname.replace(/\/+$/,'');u.search='';u.hash='';return u.toString().replace(/\/$/,'');}
function join(base,p){return new URL(p,base.endsWith('/')?base:base+'/').toString();}
function maskRtsp(url){return String(url).replace(/(rtsp:\/\/[^:@/]+:)([^@/]*)(@)/i,'$1******$3');}
function validHost(raw){const h=String(raw||'').trim();if(!h||h.length>253||/[:/\\?#@\s]/.test(h))throw new Error('DVR Host 只能填 IP 或網域名稱');if(net.isIP(h))return h;if(!/^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$/.test(h))throw new Error('DVR Host 格式不正確');return h;}
function parsePorts(raw){const src=String(raw||'').trim();const vals=src?src.split(','):DEFAULT_PORTS;return uniq(vals.map(x=>Number(String(x).trim())).filter(x=>Number.isInteger(x)&&x>=1&&x<=65535)).slice(0,16);}
function parsePaths(raw){const src=String(raw||'').trim();const vals=src?src.split(/[\r\n,]+/):COMMON_RTSP_PATHS;return uniq(vals.map(x=>{let p=String(x).trim();if(!p)return '';if(!p.startsWith('/'))p='/'+p;return p.slice(0,300);})).slice(0,24);}
function makeRtsp({host,port,user,password,path}){const auth=user?`${encodeURIComponent(user)}:${encodeURIComponent(password||'')}@`:'';return `rtsp://${auth}${host}:${port}${path}`;}

function tcpProbe(host,port,timeoutMs=1800){return new Promise(resolve=>{const t0=Date.now();const s=net.createConnection({host,port});let done=false;const finish=(status,detail)=>{if(done)return;done=true;s.destroy();resolve({port,status,detail,elapsed_ms:Date.now()-t0});};s.setTimeout(timeoutMs);s.once('connect',()=>finish('OPEN','TCP connected'));s.once('timeout',()=>finish('TIMEOUT',`timeout after ${timeoutMs} ms`));s.once('error',e=>finish('CLOSED',e.code||e.message));});}
function requestBuffer(url,timeoutMs=5000,maxBytes=1024*1024){return new Promise(resolve=>{const t0=Date.now();let settled=false,total=0;const chunks=[];const u=new URL(url);const lib=u.protocol==='https:'?https:http;const req=lib.get(u,{headers:{'User-Agent':VERSION,'Accept':'*/*'}},res=>{res.on('data',c=>{if(total<maxBytes){const x=c.slice(0,maxBytes-total);chunks.push(x);total+=x.length;}if(total>=maxBytes)req.destroy();});res.on('end',()=>finish({status:res.statusCode||0,headers:res.headers,body:Buffer.concat(chunks),ok:(res.statusCode||0)>=200&&(res.statusCode||0)<300,error:null}));});const timer=setTimeout(()=>{req.destroy(new Error('timeout'));},timeoutMs);function finish(x){if(settled)return;settled=true;clearTimeout(timer);resolve({...x,elapsed_ms:Date.now()-t0});}req.once('error',e=>finish({status:0,headers:{},body:Buffer.concat(chunks),ok:false,error:e.message}));});}
function runProcess(cmd,args,timeoutMs,maxBytes=512*1024){return new Promise(resolve=>{const t0=Date.now();let out=Buffer.alloc(0),err=Buffer.alloc(0),timed=false,spawnErr=null;const child=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});const add=(a,c)=>a.length>=maxBytes?a:Buffer.concat([a,c.slice(0,maxBytes-a.length)]);child.stdout.on('data',c=>out=add(out,c));child.stderr.on('data',c=>err=add(err,c));child.once('error',e=>spawnErr=e);const timer=setTimeout(()=>{timed=true;child.kill('SIGKILL');},timeoutMs);child.once('close',(code,signal)=>{clearTimeout(timer);resolve({code,signal,timed_out:timed,spawn_error:spawnErr?spawnErr.message:null,stdout:out,stderr:err,elapsed_ms:Date.now()-t0});});});}
async function ffmpegInfo(){const [a,b]=await Promise.all([runProcess('ffmpeg',['-hide_banner','-version'],5000,64*1024),runProcess('ffprobe',['-hide_banner','-version'],5000,64*1024)]);const fmt=r=>{const text=Buffer.concat([r.stdout,r.stderr]).toString('utf8');return {ok:!r.spawn_error&&r.code===0,first_line:text.split(/\r?\n/)[0]||'',elapsed_ms:r.elapsed_ms,error:r.spawn_error};};return {ffmpeg:fmt(a),ffprobe:fmt(b)};}
async function ffprobeRtsp(url,transport,timeoutMs){const r=await runProcess('ffprobe',['-v','error','-rtsp_transport',transport,'-rw_timeout',String(timeoutMs*1000),'-show_entries','format=format_name,duration:stream=index,codec_type,codec_name,width,height,r_frame_rate,avg_frame_rate','-of','json',url],timeoutMs+1500,256*1024);let parsed=null;try{parsed=JSON.parse(r.stdout.toString('utf8'));}catch{}const video=parsed?.streams?.find(s=>s.codec_type==='video')||null;return {ok:r.code===0&&!!video,elapsed_ms:r.elapsed_ms,timed_out:r.timed_out,exit_code:r.code,video,log:r.stderr.toString('utf8').slice(0,6000)};}
async function captureFrame(url,transport,timeoutMs){const r=await runProcess('ffmpeg',['-hide_banner','-loglevel','warning','-rtsp_transport',transport,'-rw_timeout',String(timeoutMs*1000),'-i',url,'-an','-frames:v','1','-f','image2pipe','-vcodec','mjpeg','pipe:1'],timeoutMs+2500,4*1024*1024);const b=r.stdout;const ok=r.code===0&&b.length>=4&&b[0]===0xff&&b[1]===0xd8&&b[b.length-2]===0xff&&b[b.length-1]===0xd9;return {ok,elapsed_ms:r.elapsed_ms,timed_out:r.timed_out,exit_code:r.code,jpeg_bytes:b.length,log:r.stderr.toString('utf8').slice(0,6000)};}
function discoverFromHtml(text){
  if(!text)return[];
  const out=[];
  const patterns=[
    /(?:src|href)\s*=\s*["']([^"']+)["']/gi,
    /fetch\s*\(\s*["']([^"']+)["']/gi,
    /new\s+WebSocket\s*\(\s*["']([^"']+)["']/gi
  ];
  for(const re of patterns){
    let m;
    while((m=re.exec(text))){
      try{
        const value=m[1];
        if(value.startsWith('/')){
          const parsed=new URL(value,'http://x');
          out.push(parsed.pathname+parsed.search);
        }
      }catch{}
    }
  }
  return uniq(out);
}

function parseStatus(obj){if(!obj||typeof obj!=='object')return{};return {state:obj.state??obj.status??null,current_channel:obj.current_channel??obj.channel??null,target_channel:obj.target_channel??null,fps:obj.output_fps??obj.fps??null,frame_age_ms:obj.latest_age_ms??obj.frame_age_ms??null,clients:obj.clients??null,source:obj.source??null,ffmpeg_alive:obj.ffmpeg_alive??null,version:obj.version??null};}
function testMjpeg(url,timeoutMs=10000){return new Promise(resolve=>{const t0=Date.now();let settled=false,buf=Buffer.alloc(0),frames=[];const u=new URL(url);const lib=u.protocol==='https:'?https:http;const req=lib.get(u,{headers:{'User-Agent':VERSION,'Accept':'multipart/x-mixed-replace,image/jpeg,*/*'}},res=>{const ct=String(res.headers['content-type']||'');if((res.statusCode||0)<200||(res.statusCode||0)>=300)return finish({ok:false,status:res.statusCode||0,content_type:ct,error:`HTTP ${res.statusCode}`,frames:0,bytes:[]});res.on('data',c=>{buf=Buffer.concat([buf,c]);if(buf.length>8*1024*1024)buf=buf.slice(-4*1024*1024);while(true){const a=buf.indexOf(Buffer.from([0xff,0xd8]));if(a<0)break;const z=buf.indexOf(Buffer.from([0xff,0xd9]),a+2);if(z<0)break;const jpg=buf.slice(a,z+2);frames.push(jpg);buf=buf.slice(z+2);if(frames.length>=2){req.destroy();return finish({ok:true,status:res.statusCode||200,content_type:ct,error:null,frames:2,bytes:frames.map(x=>x.length),distinct:!frames[0].equals(frames[1])});}}});res.once('end',()=>finish({ok:frames.length>0,status:res.statusCode||0,content_type:ct,error:frames.length?'stream ended':'no JPEG',frames:frames.length,bytes:frames.map(x=>x.length),distinct:frames.length>=2?!frames[0].equals(frames[1]):null}));});const timer=setTimeout(()=>{req.destroy();finish({ok:frames.length>0,status:0,content_type:'',error:frames.length?'timeout after JPEG':'frame timeout',frames:frames.length,bytes:frames.map(x=>x.length),distinct:frames.length>=2?!frames[0].equals(frames[1]):null});},timeoutMs);function finish(x){if(settled)return;settled=true;clearTimeout(timer);resolve({...x,url,elapsed_ms:Date.now()-t0});}req.once('error',e=>{if(e.code==='ECONNRESET'&&frames.length>=2)return;finish({ok:false,status:0,content_type:'',error:e.message,frames:frames.length,bytes:frames.map(x=>x.length)});});});}

async function runGatewayScan(input){const started=Date.now();const base=normalizeBase(input.gateway_url||'http://127.0.0.1:8080');const timeout=clamp(input.timeout_ms,500,30000,5000),frameTimeout=clamp(input.frame_timeout_ms,1000,60000,10000);const u=new URL(base);const report={version:VERSION,module:'GATEWAY_DIAGNOSTIC_V2_COMPAT',generated_at:new Date().toISOString(),input:{gateway_url:base,timeout_ms:timeout,frame_timeout_ms:frameTimeout},environment:{...environment(),loopback:['127.0.0.1','localhost','::1'].includes(u.hostname),target_private:isPrivateHost(u.hostname)},gateway:{},pages:[],discovered_paths:[],api_attempts:[],stream_attempts:[]};report.gateway.tcp=await tcpProbe(u.hostname,Number(u.port||(u.protocol==='https:'?443:80)),timeout);if(report.gateway.tcp.status!=='OPEN'){report.conclusion={code:'GATEWAY_TCP_UNREACHABLE',title:'無法連線 Gateway TCP Port',detail:report.gateway.tcp.detail};report.elapsed_ms=Date.now()-started;lastGatewayReport=report;return report;}
let liveHtml='';for(const p of ['/live.html','/']){const r=await requestBuffer(join(base,p),timeout);const text=r.body.toString('utf8');report.pages.push({path:p,status:r.status,ok:r.ok,content_type:r.headers['content-type']||'',elapsed_ms:r.elapsed_ms,bytes:r.body.length,title:(text.match(/<title[^>]*>([^<]+)/i)||[])[1]||null});if(r.ok&&/text\/html/i.test(String(r.headers['content-type']||''))&&!liveHtml)liveHtml=text;}report.discovered_paths=discoverFromHtml(liveHtml);
let best=null;for(const p of uniq(['/status','/health','/api/channel','/api/status','/api/health','/status.json',...report.discovered_paths.filter(x=>/status|health|channel|state/i.test(x))])){const r=await requestBuffer(join(base,p),timeout,512*1024);let obj=null;try{obj=JSON.parse(r.body.toString('utf8'));}catch{}const parsed=parseStatus(obj);report.api_attempts.push({path:p,status:r.status,ok:r.ok,json_ok:!!obj,elapsed_ms:r.elapsed_ms,content_type:r.headers['content-type']||'',parsed,preview:obj?null:r.body.toString('utf8').slice(0,160)});if(obj&&Object.values(parsed).some(v=>v!==null)&&(!best||p==='/status'))best={path:p,obj,parsed};}if(best){report.gateway.status_path=best.path;Object.assign(report.gateway,best.parsed);report.gateway.raw_status=best.obj;}
const self=report.api_attempts.some(x=>x.parsed?.version===VERSION)||report.pages.some(x=>String(x.title||'').includes('SYSTEM_DIAGNOSTIC_SUITE'));report.environment.self_loop_detected=self;if(self){report.conclusion={code:'SCANNER_LOOPBACK_POINTS_TO_ITSELF',title:'Gateway URL 指向診斷工具自己',detail:isRailway()?'Railway 的 127.0.0.1 是 Railway 容器自己，不是 Windows Gateway。':'Suite 預設使用 8090；Gateway 應使用 8080。請確認 Gateway Base URL。'};report.elapsed_ms=Date.now()-started;lastGatewayReport=report;return report;}
let selected=null;for(const p of uniq([...report.discovered_paths.filter(x=>/mjpg|mjpeg|stream|camera/i.test(x)),'/stream.mjpg','/api/camera/stream','/mjpeg','/video.mjpg'])){const a=await testMjpeg(join(base,p),frameTimeout);report.stream_attempts.push({path:p,...a});if(a.ok&&a.frames>=1){selected={path:p,...a};break;}}report.stream=selected?{ok:true,selected_path:selected.path,frames:selected.frames,bytes:selected.bytes,distinct:selected.distinct,elapsed_ms:selected.elapsed_ms}:{ok:false,selected_path:null};if(selected&&selected.frames>=2&&selected.distinct!==false)report.conclusion={code:'GATEWAY_END_TO_END_SUCCESS',title:'Gateway 端到端診斷成功',detail:'Gateway 狀態與連續 MJPEG 影格均正常。'};else if(selected)report.conclusion={code:'GATEWAY_JPEG_SINGLE_FRAME_ONLY',title:'已取得 JPEG，但尚未確認連續更新',detail:'延長影格逾時後再測試。'};else if(!liveHtml)report.conclusion={code:'GATEWAY_LIVE_PAGE_UNAVAILABLE',title:'Gateway TCP 可連，但 live.html 無法讀取',detail:'請確認 Gateway 已啟動且 Base URL/Port 正確。'};else report.conclusion={code:'GATEWAY_STREAM_PATH_NOT_FOUND',title:'找不到可用 MJPEG 路徑',detail:'請查看自動發現與串流探測結果。'};report.elapsed_ms=Date.now()-started;lastGatewayReport=report;return report;}

async function runDvrScan(input){const started=Date.now();const host=validHost(input.dvr_host||'192.168.0.123');const rtspPort=clamp(input.rtsp_port,1,65535,554),tcpTimeout=clamp(input.tcp_timeout_ms,300,15000,1800),probeTimeout=clamp(input.probe_timeout_ms,1500,30000,6000),transport=input.transport==='udp'?'udp':'tcp',ports=parsePorts(input.ports),paths=parsePaths(input.rtsp_paths);const report={version:VERSION,module:'DVR_NETWORK_RTSP_FFMPEG_V1_COMPAT',generated_at:new Date().toISOString(),input:{dvr_host:host,rtsp_port:rtspPort,user:String(input.user||''),password_masked:input.password?'******':'',transport,ports,rtsp_paths:paths,tcp_timeout_ms:tcpTimeout,probe_timeout_ms:probeTimeout},environment:environment(),host_type:isPrivateHost(host)?'PRIVATE_LAN':'PUBLIC_OR_DOMAIN',network:[],ffmpeg:await ffmpegInfo(),rtsp:{attempts:[],success:null}};for(const p of ports)report.network.push(await tcpProbe(host,p,tcpTimeout));if(!report.ffmpeg.ffmpeg.ok||!report.ffmpeg.ffprobe.ok){report.conclusion={code:'FFMPEG_OR_FFPROBE_UNAVAILABLE',title:'FFmpeg／FFprobe 不可用',detail:'請安裝 FFmpeg 並確認 ffmpeg、ffprobe 已加入 PATH。'};report.elapsed_ms=Date.now()-started;lastDvrReport=report;return report;}
for(const path of paths){const url=makeRtsp({host,port:rtspPort,user:String(input.user||''),password:String(input.password||''),path});const probe=await ffprobeRtsp(url,transport,probeTimeout);let frame=null;if(probe.ok)frame=await captureFrame(url,transport,probeTimeout);const item={path,url:maskRtsp(url),probe,frame};report.rtsp.attempts.push(item);if(probe.ok&&frame?.ok){report.rtsp.success=item;break;}}
const rtspTcp=report.network.find(x=>x.port===rtspPort);if(report.rtsp.success)report.conclusion={code:'RTSP_AND_FFMPEG_SUCCESS',title:'DVR RTSP 與 FFmpeg 測試成功',detail:`找到可用路徑 ${report.rtsp.success.path}，並擷取 JPEG。`};else if(report.host_type==='PRIVATE_LAN'&&isRailway())report.conclusion={code:'PRIVATE_LAN_NOT_REACHABLE_FROM_RAILWAY',title:'Railway 無法直接存取 DVR 私有網段',detail:`${host} 為私有 LAN 位址；請使用本機 Gateway、VPN、反向通道或主動 Relay。`};else if(!rtspTcp||rtspTcp.status!=='OPEN')report.conclusion={code:'RTSP_TCP_PORT_UNREACHABLE',title:'RTSP TCP Port 無法連線',detail:`${host}:${rtspPort} 未開啟或無法到達。`};else report.conclusion={code:'RTSP_PATH_OR_AUTH_FAILED',title:'RTSP Port 可達，但路徑或帳密未成功',detail:'請確認帳號、密碼、通道路徑及 RTSP Transport。'};report.elapsed_ms=Date.now()-started;lastDvrReport=report;return report;}

async function runSystem(input){const started=Date.now();const [gateway,dvr]=await Promise.all([runGatewayScan(input),runDvrScan(input)]);const gatewayOk=gateway.conclusion.code==='GATEWAY_END_TO_END_SUCCESS';const dvrOk=dvr.conclusion.code==='RTSP_AND_FFMPEG_SUCCESS';let conclusion;if(gatewayOk&&dvrOk)conclusion={code:'RT7_SYSTEM_ALL_LOCAL_PATHS_SUCCESS',title:'RT7 DVR 本機系統診斷成功',detail:'DVR RTSP、FFmpeg、Native Gateway 與 MJPEG 均正常。'};else if(gatewayOk)conclusion={code:'GATEWAY_SUCCESS_DVR_DIRECT_TEST_INCOMPLETE',title:'Native Gateway 正常；DVR 直接測試未完全成功',detail:'目前可維持 Gateway 架構，並查看 DVR 模組的帳密、路徑或網路結果。'};else if(dvrOk)conclusion={code:'DVR_RTSP_SUCCESS_GATEWAY_FAILED',title:'DVR RTSP 正常，但 Native Gateway 診斷失敗',detail:'請檢查 Gateway 是否啟動、Port 8080 是否正確及 /stream.mjpg 是否存在。'};else conclusion={code:'SYSTEM_DIAGNOSTIC_FAILED',title:'DVR 與 Gateway 尚未通過完整診斷',detail:'請依兩個模組的結論逐項修正。'};const report={version:VERSION,module:'FULL_SYSTEM',generated_at:new Date().toISOString(),environment:environment(),gateway,dvr,summary:{gateway_ok:gatewayOk,dvr_rtsp_ok:dvrOk,ffmpeg_ok:dvr.ffmpeg?.ffmpeg?.ok===true,ffprobe_ok:dvr.ffmpeg?.ffprobe?.ok===true,cloud_direct_ready:dvrOk&&dvr.host_type!=='PRIVATE_LAN',need_gateway:!(dvrOk&&dvr.host_type!=='PRIVATE_LAN')},conclusion,elapsed_ms:Date.now()-started};lastReport=report;return report;}

function layout(content){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${VERSION}</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#071116;color:#eef6fa;font-family:Arial,"Noto Sans TC",sans-serif}.wrap{max-width:1180px;margin:auto;padding:24px 16px 60px}.card{background:#101d23;border:1px solid #31454f;border-radius:14px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.full{grid-column:1/-1}label{display:block;color:#bcd0db;margin:0 0 5px}input,select,textarea,button{width:100%;padding:11px;border-radius:8px;border:1px solid #47606c;background:#071116;color:#fff;font-size:15px}textarea{min-height:105px}button{background:#1977b6;border:0;font-weight:700;cursor:pointer}.secondary{background:#344b58}.ok{color:#35d07f}.bad{color:#ff6565}.warn{color:#ffc84d}.muted{color:#9fb2bc}.result{font-size:22px;font-weight:800}.metric{font-size:22px;font-weight:800}.code{font:13px Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#03090c;padding:12px;border-radius:8px;max-height:420px;overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px 6px;border-bottom:1px solid #2c4049;vertical-align:top}code{color:#b9e4ff}@media(max-width:760px){.grid,.grid3{grid-template-columns:1fr}.full{grid-column:auto}}</style></head><body><main class="wrap">${content}</main></body></html>`;}
function commonForm(action,label){return `<form class="card grid" method="post" action="${action}"><div class="full"><h2>${label}</h2></div><div class="full"><label>Native Gateway Base URL</label><input name="gateway_url" value="${esc(process.env.RT7_GATEWAY_URL||'http://127.0.0.1:8080')}"></div><div><label>DVR Host</label><input name="dvr_host" value="${esc(process.env.RT7_DVR_HOST||'192.168.0.123')}"></div><div><label>RTSP Port</label><input name="rtsp_port" type="number" value="554"></div><div><label>DVR User</label><input name="user" value="admin"></div><div><label>DVR Password</label><input name="password" type="password" value="password"></div><div><label>RTSP Transport</label><select name="transport"><option value="tcp">TCP</option><option value="udp">UDP</option></select></div><div><label>TCP Ports</label><input name="ports" value="80,443,554,8000,8554,8899,34567"></div><div class="full"><label>RTSP Paths（逗號或換行分隔）</label><textarea name="rtsp_paths">/main_0,/main_1,/main_2,/main_3</textarea></div><div><label>TCP timeout ms</label><input name="tcp_timeout_ms" type="number" value="1800"></div><div><label>RTSP probe timeout ms</label><input name="probe_timeout_ms" type="number" value="6000"></div><div><label>Gateway timeout ms</label><input name="timeout_ms" type="number" value="5000"></div><div><label>MJPEG frame timeout ms</label><input name="frame_timeout_ms" type="number" value="10000"></div><div class="full"><button>${label}</button></div></form>`;}
function home(){const env=environment();return layout(`<h1>RT7 DVR System Diagnostic Suite V1</h1><div class="card"><div class="grid3"><div><div class="muted">執行平台</div><div class="metric">${esc(env.platform)}</div></div><div><div class="muted">Railway</div><div class="metric ${env.railway?'warn':'ok'}">${env.railway?'YES':'NO'}</div></div><div><div class="muted">Suite Port</div><div class="metric">${PORT}</div></div></div><p>本工具已合併 Network + RTSP + FFmpeg Scanner V1 與 Gateway Diagnostic Scanner V2。</p><p class="warn">本機完整測試：先啟動 Native RTSP Gateway，再執行本 BAT；Gateway 使用 8080，Suite 使用 8090。</p></div><div class="grid3"><form class="card" method="get" action="/system"><h2>完整系統診斷</h2><p>DVR、RTSP、FFmpeg、Gateway、MJPEG 一次完成。</p><button>開啟</button></form><form class="card" method="get" action="/gateway"><h2>Gateway 診斷</h2><p>相容原 Gateway Diagnostic Scanner V2。</p><button>開啟</button></form><form class="card" method="get" action="/dvr"><h2>DVR 能力診斷</h2><p>相容原 Network + RTSP + FFmpeg Scanner V1。</p><button>開啟</button></form></div>`);}
function parseForm(p){return {gateway_url:p.get('gateway_url'),dvr_host:p.get('dvr_host'),rtsp_port:p.get('rtsp_port'),user:p.get('user'),password:p.get('password'),transport:p.get('transport'),ports:p.get('ports'),rtsp_paths:p.get('rtsp_paths'),tcp_timeout_ms:p.get('tcp_timeout_ms'),probe_timeout_ms:p.get('probe_timeout_ms'),timeout_ms:p.get('timeout_ms'),frame_timeout_ms:p.get('frame_timeout_ms')};}
function badge(ok){return `<span class="${ok?'ok':'bad'}">${ok?'PASS':'FAIL'}</span>`;}
function gatewayResult(r){const rows=(r.stream_attempts||[]).map(x=>`<tr><td>${esc(x.path)}</td><td>${badge(x.ok)}</td><td>${x.frames||0}</td><td>${esc((x.bytes||[]).join(', '))}</td><td>${esc(x.error||'')}</td></tr>`).join('');return layout(`<h1>Gateway 診斷結果</h1><div class="card"><div class="result ${r.conclusion.code==='GATEWAY_END_TO_END_SUCCESS'?'ok':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="card"><table><tr><th>Gateway</th><td>${esc(r.input.gateway_url)}</td></tr><tr><th>TCP</th><td>${esc(r.gateway.tcp?.status)} — ${esc(r.gateway.tcp?.detail)}</td></tr><tr><th>Gateway Version</th><td>${esc(r.gateway.version||'-')}</td></tr><tr><th>State / CH</th><td>${esc(r.gateway.state??'-')} / ${esc(r.gateway.current_channel??'-')} → ${esc(r.gateway.target_channel??'-')}</td></tr><tr><th>FPS / Age / Clients</th><td>${esc(r.gateway.fps??'-')} / ${esc(r.gateway.frame_age_ms??'-')} ms / ${esc(r.gateway.clients??'-')}</td></tr><tr><th>Stream</th><td>${esc(r.stream?.selected_path||'-')}</td></tr></table></div><div class="card"><h2>MJPEG 探測</h2><table><tr><th>Path</th><th>結果</th><th>Frames</th><th>Bytes</th><th>錯誤</th></tr>${rows||'<tr><td colspan="5">未執行</td></tr>'}</table></div><div class="grid"><form method="get" action="/gateway"><button>重新測試</button></form><form method="get" action="/api/last-gateway-report"><button class="secondary">JSON 報告</button></form></div>`);}
function dvrResult(r){const netRows=r.network.map(x=>`<tr><td>${x.port}</td><td>${badge(x.status==='OPEN')}</td><td>${esc(x.status)}</td><td>${esc(x.detail)}</td><td>${x.elapsed_ms} ms</td></tr>`).join('');const rtspRows=r.rtsp.attempts.map(x=>`<tr><td>${esc(x.path)}</td><td>${badge(x.probe.ok)}</td><td>${badge(x.frame?.ok===true)}</td><td>${esc(x.probe.video?.codec_name||'-')}</td><td>${esc(x.probe.video?`${x.probe.video.width||'-'}x${x.probe.video.height||'-'}`:'-')}</td><td>${x.frame?.jpeg_bytes||0}</td></tr>`).join('');return layout(`<h1>DVR Network + RTSP + FFmpeg 結果</h1><div class="card"><div class="result ${r.conclusion.code==='RTSP_AND_FFMPEG_SUCCESS'?'ok':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="grid3"><div class="card"><div class="muted">FFmpeg</div><div class="metric">${badge(r.ffmpeg.ffmpeg.ok)}</div><small>${esc(r.ffmpeg.ffmpeg.first_line||r.ffmpeg.ffmpeg.error||'')}</small></div><div class="card"><div class="muted">FFprobe</div><div class="metric">${badge(r.ffmpeg.ffprobe.ok)}</div><small>${esc(r.ffmpeg.ffprobe.first_line||r.ffmpeg.ffprobe.error||'')}</small></div><div class="card"><div class="muted">Host Type</div><div class="metric">${esc(r.host_type)}</div></div></div><div class="card"><h2>TCP Port</h2><table><tr><th>Port</th><th>結果</th><th>狀態</th><th>資訊</th><th>耗時</th></tr>${netRows}</table></div><div class="card"><h2>RTSP 路徑</h2><table><tr><th>Path</th><th>Probe</th><th>JPEG</th><th>Codec</th><th>Size</th><th>JPEG Bytes</th></tr>${rtspRows||'<tr><td colspan="6">未執行</td></tr>'}</table></div><div class="grid"><form method="get" action="/dvr"><button>重新測試</button></form><form method="get" action="/api/last-dvr-report"><button class="secondary">JSON 報告</button></form></div>`);}
function systemResult(r){return layout(`<h1>RT7 完整系統診斷結果</h1><div class="card"><div class="result ${r.conclusion.code==='RT7_SYSTEM_ALL_LOCAL_PATHS_SUCCESS'?'ok':'bad'}">${esc(r.conclusion.code)}</div><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.detail)}</p></div><div class="grid3"><div class="card"><div class="muted">DVR RTSP</div><div class="metric">${badge(r.summary.dvr_rtsp_ok)}</div><p>${esc(r.dvr.conclusion.code)}</p></div><div class="card"><div class="muted">Native Gateway</div><div class="metric">${badge(r.summary.gateway_ok)}</div><p>${esc(r.gateway.conclusion.code)}</p></div><div class="card"><div class="muted">FFmpeg / FFprobe</div><div class="metric">${badge(r.summary.ffmpeg_ok&&r.summary.ffprobe_ok)}</div></div></div><div class="card"><table><tr><th>Cloud Direct Ready</th><td>${r.summary.cloud_direct_ready?'YES':'NO'}</td></tr><tr><th>Need Gateway</th><td>${r.summary.need_gateway?'YES':'NO'}</td></tr><tr><th>Gateway Stream</th><td>${esc(r.gateway.stream?.selected_path||'-')}</td></tr><tr><th>RTSP Success Path</th><td>${esc(r.dvr.rtsp?.success?.path||'-')}</td></tr><tr><th>總耗時</th><td>${r.elapsed_ms} ms</td></tr></table></div><div class="grid"><form method="get" action="/system"><button>重新測試</button></form><form method="get" action="/api/last-report"><button class="secondary">完整 JSON 報告</button></form></div>`);}
async function readBody(req){let body='';req.setEncoding('utf8');for await(const c of req){body+=c;if(body.length>MAX_BODY)throw new Error('request too large');}return new URLSearchParams(body);}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/')return html(res,200,home());if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,version:VERSION,environment:environment(),port:PORT});if(req.method==='GET'&&u.pathname==='/system')return html(res,200,layout(`<h1>完整系統診斷</h1>${commonForm('/run/system','開始完整系統診斷')}`));if(req.method==='GET'&&u.pathname==='/gateway')return html(res,200,layout(`<h1>Native Gateway 診斷</h1>${commonForm('/run/gateway','開始 Gateway 診斷')}`));if(req.method==='GET'&&u.pathname==='/dvr')return html(res,200,layout(`<h1>DVR Network + RTSP + FFmpeg</h1>${commonForm('/run/dvr','開始 DVR 能力診斷')}`));if(req.method==='GET'&&u.pathname==='/api/last-report')return json(res,lastReport?200:404,lastReport||{ok:false,error:'no_report'});if(req.method==='GET'&&u.pathname==='/api/last-gateway-report')return json(res,lastGatewayReport?200:404,lastGatewayReport||{ok:false,error:'no_gateway_report'});if(req.method==='GET'&&u.pathname==='/api/last-dvr-report')return json(res,lastDvrReport?200:404,lastDvrReport||{ok:false,error:'no_dvr_report'});if(req.method==='POST'&&u.pathname.startsWith('/run/')){const input=parseForm(await readBody(req));if(u.pathname==='/run/gateway')return html(res,200,gatewayResult(await runGatewayScan(input)));if(u.pathname==='/run/dvr')return html(res,200,dvrResult(await runDvrScan(input)));if(u.pathname==='/run/system')return html(res,200,systemResult(await runSystem(input)));}return json(res,404,{ok:false,error:'not_found'});}catch(e){return html(res,500,layout(`<h1 class="bad">Diagnostic Error</h1><div class="card code">${esc(e.stack||e)}</div><form method="get" action="/"><button>返回首頁</button></form>`));}});
server.listen(PORT,HOST,()=>{console.log('='.repeat(76));console.log(VERSION);console.log(`Suite:   http://127.0.0.1:${PORT}`);console.log('Gateway: http://127.0.0.1:8080/live.html');console.log('='.repeat(76));});
